name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: install
      run: >
        sudo apt-get update && sudo apt-get --no-install-recommends -y install
        cmake
    - name: build
      run: >
        mkdir cmake ;
        cd cmake ;
        cmake .. ;
        make
